"""Add Review Model

Revision ID: 4a0d955c60da
Revises: d783730ef855
Create Date: 2025-06-04 08:41:37.130412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0d955c60da'
down_revision = 'd783730ef855'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
