"""Add Review Model

Revision ID: 4d0ceb57b6f1
Revises: 4a0d955c60da
Create Date: 2025-06-04 08:41:47.995886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0ceb57b6f1'
down_revision = '4a0d955c60da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
